### PR TITLE
gnu_legacy: with GNU, write foreground first, else background first.

### PR DESCRIPTION
**Pull request by sylvestre**
Fixes:
https://github.com/sharkdp/lscolors/issues/77

### CODE REVIEW

**Comment by sylvestre** [comment]
I will update lscolors and rust-coreutils after that

**Comment by fdncred** [comment]
I've been following the discussion on lscolors. This seems reasonable to me.

**Comment by sylvestre** [comment]
@fdncred thanks. Would it be possible to merge this PR and do a new release of this crate? thanks

**Comment by fdncred** [comment]
I'm fine with it. @sholderbach what do you think? do you have time to publish a release here?

**Comment by sholderbach** [comment]
Looks good!

I can take care of shipping the release later. 

For Nushell/Reedline we would wait on the next lscolors release if we go for a minor version. Alternatively we could ship this as a patch release (API and overall design is constant, but the change in behavior could break tests for folks)

I would favor going with `0.50.0` for the release.

**Comment by sylvestre** [comment]
@sholderbach thanks!

**Comment by sylvestre** [comment]
@sholderbach sorry for the pressure but do you have an eta for the new release? thanks

**Comment by fdncred** [comment]
@sylvestre I'm trying to find someone else on the nushell team to do a release. Sorry it's taking so long.

**Comment by fdncred** [comment]
@sylvestre FYI - Kubouch was able to do a release for us. nu-ansi-term 0.50 is in crates.io now. We're kind of stuck now in nushell because we're waiting on a lscolors release to update to the latest nu-ansi-term, lol.

**Comment by sylvestre** [comment]
thanks!

**Pull request merged**
