### PR TITLE
Add const on some functions

### PR DESCRIPTION
**Pull request by jaudiger**
Constify some functions, in order to use them in const context for other crates.

### CODE REVIEW

**Comment by nickelc** [comment]
If you move the `Style::default()` details into a private `Style::const_default` method then you can also constify `Style::new()` and `Style::is_plain()`.

**Comment by sholderbach** [comment]
I know for nushell it doesn't matter as much as we are pretty aggressive in that regard but do we want to commit to a certain minimum supported Rust version? Then I am not fully up to speed how far we can go with constification without precluding certain users.

**Comment by jaudiger** [comment]
I can revert some const functions if needed. For example, to not enforce a specific rust version, I can remove the const keywords when the saturating functions are involved, and so on. What your thoughts on that?

I can suggest two approaches for now:

- imply const on easy functions that don’t rely on sub const functions from rust
- or just close this PR

**Comment by jaudiger** [comment]
At a certain point, my initial assumption was: most of the API exposed by this crate could be const. Since there is no a strong logic in there. And I was thinking that enforcing this trait could make sense for the end users. Anyway, you’re right about the no usage of a rust version as of today.

Just let me know, what would you prefer.

**Comment by nickelc** [comment]
I've tested the PR with `cargo msrv` and it bumps the MSRV from 1.56 to 1.61.

**Comment by sholderbach** [comment]
> I've tested the PR with `cargo msrv` and it bumps the MSRV from 1.56 to 1.61.

Thanks for investigating that!

For the stuff I am doing both would be fine.

**Comment by jaudiger** [comment]
So, what's next @sholderbach? Should I enforce the usage of the Rust version in cargo.toml without doing any further modifications?

About your comment @nickelc, [bevy](https://bevyengine.org/) did already that in their latest release (https://bevyengine.org/news/bevy-0-10/#const-bevy-ui-defaults). It could enable the usage of `const` in additional functions until Rust enables it inside the `Default` trait.

**Comment by jaudiger** [comment]
I just rebased this PR on main, and I add the field `rust-version` inside Cargo.toml.

**Comment by jaudiger** [comment]
@fdncred I don't know what is the current strategy regarding const functions. At least, the MSRV now announced is 1.62.1 with https://github.com/nushell/nu-ansi-term/pull/30. There is no more blocker regarding adding those const keywords.

But I'm open to any discussion. I could reduce the set of APIs using const, or we can even close it if this is not the right time !

**Comment by sholderbach** [comment]
As we already bumped the MSRV for that default syntactic sugar we can go ahead with this constification.

**Pull request merged**
