### PR TITLE
added `ESC[22m` to reset bold and dim

### PR DESCRIPTION
**Pull request by rsteube**
https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#colors--graphics-mode

### CODE REVIEW

**Comment by rsteube** [comment]
Updated the test but have not verified it. Someone needs to confirm that adding this is fine.

**Comment by fdncred** [comment]
This doesn't seem correct to me. Reset is just 0m not 0;22m. 0m should reset everything, all styles and colors, right? I thought 22m was just to reset bold and leave everything else alone.

**Comment by rsteube** [comment]
I expected that as well but in the completion menu, which uses `RESET`, bold is kept:

image

This is pretty much a test to see if it would fix it, but I can't get the dependency replacement to work.
Probably something else that causes it, I got a bit irritated by the ansi documentation and a related issue I had with powershell.

**Comment by rsteube** [comment]
Closing this, a simple test with echo is fine. Sorry about this, think I need some sleep :sweat_smile: .

**Pull request closed without merging**
